### ISSUE TITLE
how to render a pbrt scene file

### ISSUE THREAD

**Issue by pengwang123** [giuliojiang/pbrt-v3-IILE#57]
I use ./build/pbrt  "scene path" to render. but it shows:
api.cpp: pbrtIntegrator name is iispt
nnconnectormanager.cpp: Starting NN connector 0
ERROR, environment variable IISPT_STDIO_NET_PY_PATH is not defined. Shutting down...

what's the problem, I compiled from the source code.

**Comment by giuliojiang** [comment]
Hi @pengwang123 , thanks for trying out my software.

The env variable is automatically set by the launcher `bin/pbrt`. It's a simple nodejs script that sets up some environment variable and some useful command line arguments.

`cd bin` and `npm install` to get some dependencies, and you can use `./bin/pbrt <scene.pbrt>` just as the normal pbrt executable, as other arguments are passed along.

If you prefer to use the native executable, have a look at what the launcher does here https://github.com/giuliojiang/pbrt-v3-IILE/blob/master/bin/pbrt#L53 to set the environment.

Feel free to ask more if it doesn't work or need more info.

**Comment by pengwang123** [comment]
Thanks so much for replying!!! I followed the steps. cd bin and then npm install. it shows:

npm WARN pbrt-launcher@1.0.0 No description
npm WARN pbrt-launcher@1.0.0 No repository field.

and  ./bin/pbrt  /home/.../killeroo-simple.pbrt shows errpr:

FileNotFoundError: [Errno 2] No such file or directory: 'iispt_model.tch'
childprocess.hpp: Encountered EOF after [0] bytes already read
iisptnnconnector.cpp: Error when reading float array
iisptnnconnector.cpp: An error occurred when reading output image
iisptrenderrunner.cpp: Thread 5 NN communication issue

sorry for my poor linux experience, did I missing something  that should be installed?
Thanks again!

**Comment by giuliojiang** [comment]
You can download it from https://github.com/giuliojiang/pbrt-v3-IISPT-dataset/releases/download/v4/iispt_model_f1.tch

and move (rename) it into `pbrt-v3-IILE/iispt_model.tch`

I think it's my fault as the documentation is quite lacking at the moment

**Comment by pengwang123** [comment]
It works!!! Thanks for your patience and instructions. By the way, have u published a paper for this work or there is any reference paper related to this CNN tech? It would be exciting to learn the details of it.

Thanks again!

**Comment by giuliojiang** [comment]
No worries. I'm updating the official documentation on the website to make life easier for other users.

I have a paper for this, but it's currently under review. I'll definitely add a link on the website once it's been approved (hopefully).

If you don't mind I'd be interested to know how you found out about this project.

**Comment by pengwang123** [comment]
I found here form pbrt website~it indicates that a tool for export pbrt scene file form blender.
That's great, hope to see your publication soon!!!
Thanks again!!!
Regards

**Comment by giuliojiang** [comment]
awesome

have a nice day!
