### ISSUE TITLE
How to actually export pbrt scene file?

### ISSUE THREAD

**Issue by IgrauBezRuk** [giuliojiang/pbrt-v3-IILE#58]
Hey! I've just installed your plugin but still haven't export option for pbrt scene
![default](https://user-images.githubusercontent.com/5683877/50583172-c83fce80-0e78-11e9-865e-1c3aaf627551.png)
As you can see, I followed your tutorial, chose pbrtv3 as renderer and have configuration panel in bottom right. So what can be a problem here?

**Comment by giuliojiang** [comment]
the screenshot looks fine to me.
The export isn't implemented in the export menu, but as Render. Just press F12 (default keymap) and it should start exporting.

Let me know if you need more help

**Comment by IgrauBezRuk** [comment]
Ah f12, didn't know about that, thanks. Yeah, it exported lot of files and I tried pbrt 3 of them. exp, exp2 and scene. Only scene was rendered, but also it said that no light sources in scene - ignoring.
Attaching the output
![default](https://user-images.githubusercontent.com/5683877/50649978-4e026d80-0f90-11e9-93ad-a70f4fc8ebdc.png)

**Comment by giuliojiang** [comment]
as this exporter isn't very polished, it doesn't have the full blender feature set.

The easiest way to add a supported light source is to use a cube, place it where you want your light, and give it a new material. In the materials pane set Emission to a positive value (like 10). That becomes a light source.

**Comment by IgrauBezRuk** [comment]
Okay, thanks, will try. And what is very best way to create pbrt scenes? Because I saw lot of cool scenes. Only cinema4d?

**Comment by giuliojiang** [comment]
I created this exporter specifically because I like to make my scenes in Blender.
I'm not sure what others prefer, but you can ask in the PBRT google group if you want https://groups.google.com/forum/#!forum/pbrt
Matt (the author of PBRT) is very friendly

**Comment by IgrauBezRuk** [comment]
Thank you, I will definitely ask.
You are very friendly too :)
