### ISSUE TITLE
Doesn't work with Blender 2.82

### ISSUE THREAD

**Issue by danielthompson** [giuliojiang/pbrt-v3-IILE#59]
Hello,

Thanks for putting this plugin together.

I tried downloading the plugin from [here](https://github.com/giuliojiang/pbrt-v3-IILE/releases/download/v4/pbrtExporter.zip), but after adding the plugin into Blender 2.82 on Ubuntu 18.04, I get the following error:

![image](https://user-images.githubusercontent.com/838836/82593605-5e58bf80-9b68-11ea-925b-fa7c34d92e01.png)

The rendering engine does not show in the renderer dropdown either:

![image](https://user-images.githubusercontent.com/838836/82594135-3ddd3500-9b69-11ea-87ee-75e23233e802.png)

I don't have much Python or Blender experience, but I'll try to carve out some time to look into this. Any help would be much appreciated.

**Comment by giuliojiang** [comment]
hi, thanks for creating the issue.
The plugin was developed for 2.7x, unfortunately 2.8x introduced major interface changes so the plugin doesn't work on 2.8x.

I don't have plans currently to port it for 2.8x.

I've clarified the readme https://github.com/giuliojiang/pbrt-v3-blender-exporter
